### ISSUE TITLE
Please add requirements.txt

### ISSUE THREAD

**Issue by cingtiye** [dki-lab/ArcaneQA#1]
ArcaneQA and [Pangu](https://github.com/dki-lab/Pangu) are very good jobs in QA!

When I run the code, some errors occurred due to incorrect package installation. 

So please add requirement.txt to better run the code.

Best regards.

**Comment by entslscheia** [comment]
Hi,

Thanks for your interest in our work!

We are using Conda to manage the python environments, so you may refer to the yml file directly exported from our Conda environment: https://github.com/dki-lab/ArcaneQA/blob/main/environment_arcane.yml

Best,
Yu
