### ISSUE TITLE
how to convert sparql/cypher to s-expression or inverse ?

### ISSUE THREAD

**Issue by feng-1985** [dki-lab/ArcaneQA#3]
is there any tools like this https://github.com/Flitternie/GraphQ_Trans?

**Comment by entslscheia** [comment]
Hi,

You can find our implementation for converting S-expressions to SPARQL queries via https://github.com/dki-lab/ArcaneQA/blob/8c6df7f0dc47d78f6e2df02a5570454f39d2ced4/source/utils/logical_form_util.py#L382

Also, you may find our code for converting graph query to S-expression via
https://github.com/dki-lab/ArcaneQA/blob/06122c727af4f841187074550b6020bf29b29a09/source/utils/logical_form_util.py#L232

Our implementation is a bit ad-hoc and specific to GrailQA or WebQSP. It should be good enough if you just want to work with these popular benchmarks. The tool shared by you may represent a more systematic effort (I really appreciate the contribution by the authors of GraphQ_Trans). Unfortunately, we don't have a such dedicated and generic tool so far.

Feel free to let me know if you have more questions!

**Comment by feng-1985** [comment]
Thanks !
