### ISSUE TITLE
Can you please share machine configuration

### ISSUE THREAD

**Issue by lgxccc** [dki-lab/ArcaneQA#4]
i.e., Details of GPUs used during training.
I use the rtx4070 to train the model for reproduction. The batch size is set to 1, and the "num_gradient_accumulation_steps" is set to 16. It reports 'out of memory'.

**Comment by lgxccc** [comment]
The graphics card I used was 4070, and shortly after starting my training, I was told that it exceeded the graphics memory. I switched to a 3090 graphics card, but it still told me that it exceeded the graphics memory. Could you please tell me your training configuration? Is the situation I encountered normal? 
I tried to see if the memory overflow was caused by certain specific data. When I set this specific data as the first data and performed training, it immediately prompted me that the memory overflow was caused. Please tell me what I should do, please give me some help

**Comment by entslscheia** [comment]
Hi @lgxccc ! Thanks for your interest in ArcaneQA.
I used a single 2080Ti 11G card for training, with gradient checkpointing on. Could you try to do gradient checkpointing inside the BERT model? Please let me know how it goes. Also, feel free to reach out if you have any further questions.

**Comment by lgxccc** [comment]
> Hi @lgxccc ! Thanks for your interest in ArcaneQA. I used a single 2080Ti 11G card for training, with gradient checkpointing on. Could you try to do gradient checkpointing inside the BERT model? Please let me know how it goes. Also, feel free to reach out if you have any further questions.

Sincerely thank you for your reply! I used annotated code for gradient checkpointing：
`wrappedmodel = ModelWrapper(self.model)
 processed_inputs = wrappedmodel.process_inputs(batch)
 output_dict = checkpoint(wrappedmodel, processed_inputs)`
But we cannot perform backpropagation calculations on loss because the resulting loss has no grad. 
Would you please share some details about doing gradient checkpointing? For example, the problem of not being able to calculate the gradient of loss, thank you.

**Comment by entslscheia** [comment]
No that part of code is not related to gradient checkpointing.
If you are using `transformers=3.3.1`, you can specify `gradient_checkpointing=True` in the config file of BERT (see line `459-483` in `modeling_bert.py` from `transformers`).

**Comment by lgxccc** [comment]
> No that part of code is not related to gradient checkpointing. If you are using `transformers=3.3.1`, you can specify `gradient_checkpointing=True` in the config file of BERT (see line `459-483` in `modeling_bert.py` from `transformers`).
Thank you so much for your suggestion. I have successfully resolved the issue of GPU memory overflow! I have started training now, and I have set the gradient accumulation steps to 8. However, it seems that the training process is very slow, and it appears to take more than ten days to complete the first epoch. I was wondering if you also experienced a similar duration when training?
`example_count: 448.0000, exact_match_count: 166.0000, exact_match: 0.3705, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6611 ||:   1%|          | 56/5665 [2:51:40<310:59:46, 199.61s/it]
example_count: 456.0000, exact_match_count: 170.0000, exact_match: 0.3728, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6617 ||:   1%|1         | 57/5665 [2:54:31<297:48:06, 191.17s/it]
example_count: 464.0000, exact_match_count: 175.0000, exact_match: 0.3772, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6546 ||:   1%|1         | 58/5665 [2:56:12<255:22:34, 163.97s/it]
example_count: 472.0000, exact_match_count: 179.0000, exact_match: 0.3792, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6483 ||:   1%|1         | 59/5665 [2:59:03<258:37:55, 166.09s/it]
example_count: 480.0000, exact_match_count: 185.0000, exact_match: 0.3854, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6416 ||:   1%|1         | 60/5665 [3:01:14<242:19:24, 155.64s/it]
example_count: 488.0000, exact_match_count: 187.0000, exact_match: 0.3832, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6393 ||:   1%|1         | 61/5665 [3:02:55<217:00:28, 139.41s/it]
example_count: 496.0000, exact_match_count: 189.0000, exact_match: 0.3810, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6413 ||:   1%|1         | 62/5665 [3:08:02<295:12:41, 189.68s/it]
example_count: 504.0000, exact_match_count: 194.0000, exact_match: 0.3849, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6367 ||:   1%|1         | 63/5665 [3:09:05<235:44:41, 151.50s/it]
example_count: 512.0000, exact_match_count: 197.0000, exact_match: 0.3848, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6365 ||:   1%|1         | 64/5665 [3:13:05<277:12:52, 178.18s/it]
example_count: 520.0000, exact_match_count: 203.0000, exact_match: 0.3904, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6311 ||:   1%|1         | 65/5665 [3:16:54<300:37:27, 193.26s/it]`

**Comment by lgxccc** [comment]
> No that part of code is not related to gradient checkpointing. If you are using `transformers=3.3.1`, you can specify `gradient_checkpointing=True` in the config file of BERT (see line `459-483` in `modeling_bert.py` from `transformers`).


Thank you so much for your suggestion. I have successfully resolved the issue of GPU memory overflow! I have started training now, and I have set the gradient accumulation steps to 8. However, it seems that the training process is very slow, and it appears to take more than ten days to complete the first epoch. I was wondering if you also experienced a similar duration when training?

`example_count: 496.0000, exact_match_count: 189.0000, exact_match: 0.3810, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6413 ||:   1%|1         | 62/5665 [3:08:02<295:12:41, 189.68s/it]

example_count: 504.0000, exact_match_count: 194.0000, exact_match: 0.3849, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6367 ||:   1%|1         | 63/5665 [3:09:05<235:44:41, 151.50s/it]

example_count: 512.0000, exact_match_count: 197.0000, exact_match: 0.3848, exact_match_k: 0.0000, F1: 0.0000, MRR_k: 0.0000, loss: 0.6365 ||:   1%|1         | 64/5665 [3:13:05<277:12:52, 178.18s/it]`
