### ISSUE TITLE
Can't visit the website of evaluation script

### ISSUE THREAD

**Issue by lgxccc** [dki-lab/ArcaneQA#7]
Now I want to evaluate my results. I was able to access the official [Evaluation Script](https://worksheets.codalab.org/bundles/0x2d13989c17e44690ab62cc4edc0b900d/) a few months ago, but now I can't. May I ask if you can log in to [Evaluation Script](https://worksheets.codalab.org/bundles/0x2d13989c17e44690ab62cc4edc0b900d/) now?

**Comment by ysu1989** [comment]
The Codalab service that our evaluation process is built on seems to be closed down. We will figure out another way for the evaluation as soon as possible. Thank you for the patience!

**Comment by lgxccc** [comment]
> The Codalab service that our evaluation process is built on seems to be closed down. We will figure out another way for the evaluation as soon as possible. Thank you for the patience!

okay, thanks you very muck!

**Comment by entslscheia** [comment]
@lgxccc Could you just send your prediction file to my email (gu.826@osu.edu)? I can evaluate it manually for you.
